package constant

type EventType string

const (
	INTERACTION_CREATE      EventType = "INTERACTION_CREATE"
	C2C_MESSAGE_CREATE      EventType = "C2C_MESSAGE_CREATE"
	GROUP_AT_MESSAGE_CREATE EventType = "GROUP_AT_MESSAGE_CREATE"
	GROUP_MESSAGE_CREATE    EventType = "GROUP_MESSAGE_CREATE"
	GROUP_JOIN_REQUEST      EventType = "GROUP_JOIN_REQUEST"
	MESSAGE_AUDIT_PASS      EventType = "MESSAGE_AUDIT_PASS"
	MESSAGE_AUDIT_REJECT    EventType = "MESSAGE_AUDIT_REJECT"
)
